### ISSUE TITLE
Create test pipelines with github actions

### ISSUE THREAD

**Issue by MitkoTschimev** [visual-knight/platform-community-edition#15]
I am happy that the community is helping with this project and to bring better help for the PR's we need a QA pipeline which github actions will provide the easiest way

**Comment by pashidlos** [comment]
@MitkoTschimev can I make this task?

**Comment by MitkoTschimev** [comment]
Oh please @pashidlos ! Currently, I try to find time but my capacities are fully on other projects.

**Comment by pashidlos** [comment]
@MitkoTschimev here you go
https://github.com/visual-knight/platform-community-edition/pull/18

**Comment by MitkoTschimev** [comment]
Thx! it works ;)
